name: automatic build
on:
  push:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: setup node
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 18.x
      - name: install
        run: yarn install --frozen-lockfile
      - name: build
        run: npm run build
      - name: copy
        run: |
          rm -r ./node_modules
          mkdir -p ${{ runner.temp }}/built
          cp -r . ${{ runner.temp }}/built
          rm -rf ${{ runner.temp }}/built/.git
      - name: switch branch
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          ref: built
      - name: commit
        run: |
          cp -r ./.git ${{ runner.temp }}/built/.git
          cp -f ./.gitignore ${{ runner.temp }}/built
          find . -maxdepth 1 -not -iname "." | xargs rm -r
          cp -r -T ${{ runner.temp }}/built .
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action Build"
          git add .
          git commit -m "Automatic Build"
      - name: push
        uses: ad-m/github-push-action@02b0b75d447f0098d40d0d65a3e6cdf2119e6f60
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          branch: built
